### PR TITLE
Add new fields to user and update registration form

### PR DESCRIPTION
**Pull request by yucombinator**
Added some extra fields to `User` (maybe we should rename it to `applicant` which is a better name for it). Also changed up the routes so `/apply` takes the user to the devise new user form.

Basically when the user submits an application it is actually a user registration page in desguise, so in the future we can build an application edit page into the webapp.

TODO: (maybe you can help me with this @davepagurek)
- CSS it up, it looks completely blend right now
- We probably want to add extra fields later depending on what questions we want to ask applicants, I just put a few on top of my mind right now.
- Break the application page into different `pages`, maybe this could simply be done on the client side by hiding and showing different page divs, and showing the actual submit button at the last step. Probably the easiest way of doing it.

### CODE REVIEW

**Comment by yucombinator** [comment]
Also whoa it checked in precompiled files... Thoughts about how to deal with this best? Been a while since I touched Rails

**Comment by davepagurek** [comment]
I'll clone this tomorrow and check off some of these. We can paginate in js/css pretty easily. For the precompiled assets, is there anything wrong with just .gitignoring them?

**Comment by yucombinator** [comment]
Perfect, done! I wasn't sure why that wasn't included in the default gitignore that Rails supplies.

**Comment by yucombinator** [comment]
@DeonHua Thoughts? Should the application questions live within `User` or move them into its distinct model.

**Comment by davepagurek** [comment]
Going to merge this so we can keep working concurrently, we can make further changes in other PRs

**Pull request merged**
